Privado-Inc/privado-core

build.sbt, src/main/scala/ai/privado/entrypoint/CommandParser.scala, src/main/scala/ai/privado/entrypoint/Main.scala, src/main/scala/ai/privado/exporter/JSONExporter.scala, src/main/scala/ai/privado/metric/MetricHandler.scala
Hi @khemrajrathore / @ojaswa1942, 
Changes to Stringify the Json before uploading to cloud. Also changed the key names as request by Vineet. Please have a look. 
Thank you.
cc: @pandurangpatil
=> fix: stringify json before request, change key names in metrics

src/main/scala/ai/privado/auth/AuthenticationHandler.scala, src/main/scala/ai/privado/entrypoint/ScanProcessor.scala, src/main/scala/ai/privado/metric/MetricHandler.scala
Hi @ojaswa1942 / @khemrajrathore , 
added metrics for upload and scan status. Please have a look. 
Thank you. 
cc: @pandurangpatil
=> change: update metrics for scan and upload status

build.sbt, src/main/scala/ai/privado/entrypoint/ScanProcessor.scala, src/main/scala/ai/privado/java/processor/JavaProcessor.scala, src/main/scala/ai/privado/java/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/java/tagger/collection/CollectionTagger.scala, src/main/scala/ai/privado/java/tagger/sink/APITagger.scala, src/main/scala/ai/privado/java/tagger/sink/CustomInheritTagger.scala, src/main/scala/ai/privado/java/tagger/sink/RegularSinkTagger.scala, src/main/scala/ai/privado/java/tagger/source/IdentifierTagger.scala, src/main/scala/ai/privado/javascript/processor/JavascriptProcessor.scala, src/main/scala/ai/privado/javascript/semantic/Language.scala, src/main/scala/ai/privado/javascript/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/javascript/tagger/sink/LeakageSinkTagger.scala, src/main/scala/ai/privado/javascript/tagger/source/IdentifierTagger.scala, src/main/scala/ai/privado/model/PrivadoTag.scala, src/main/scala/ai/privado/tagger/PrivadoBaseTagger.scala, src/main/scala/ai/privado/tagger/PrivadoSimplePass.scala, src/main/scala/ai/privado/tagger/source/LiteralTagger.scala
add - JsSrc2Cpg
patch - filtering rules by language after detecting language
add - sample tagger integration
=> add - JsSrc2Cpg

src/main/scala/ai/privado/entrypoint/ScanProcessor.scala
Fix for handling the exception in the issue https://github.com/Privado-Inc/privado/issues/76 
Please have a look. Thank you. 
cc: @ojaswa1942 / @pandurangpatil
=> patch: add exception handling for guessLanguage

src/main/resources/ai/privado/rulevalidator/schema/exclusions.json, src/main/resources/ai/privado/rulevalidator/schema/semantics.json, src/main/scala/ai/privado/entrypoint/RuleValidator.scala, src/main/scala/ai/privado/model/Constants.scala, src/main/scala/ai/privado/model/PrivadoTag.scala, src/main/scala/ai/privado/rulevalidator/YamlFileValidator.scala
@HiteshMah-Jan, added changes for parsing config rules (semantics and exclusions). Please have a look. 
Thank you. 
cc: @khemrajrathore / @pandurangpatil
=> feature: changes for config rule vaidation

src/main/scala/ai/privado/exporter/ConsoleExporter.scala, src/main/scala/ai/privado/languageEngine/javascript/passes/methodfullname/MethodFullName.scala, src/main/scala/ai/privado/languageEngine/javascript/passes/methodfullname/MethodFullNameFromIdentifier.scala, src/test/scala/ai/privado/languageEngine/java/passes/config/PropertiesFilePassTest.scala, src/test/scala/ai/privado/languageEngine/javascript/JavascriptTaggingTestBase.scala, src/test/scala/ai/privado/languageEngine/javascript/passes/methodfullname/JavascriptMethodFullNamePassTest.scala, src/test/scala/ai/privado/languageEngine/javascript/tagger/source/JavascriptIdentifierTaggingTest.scala
note - testCase failing as package.json is not read currently in test, Have raised a query for that, once that is responded back will make respective changes
=> add - test case for methodFullName pass

.gitignore, build.sbt, src/main/scala/ai/privado/cache/DatabaseDetailsCache.scala, src/main/scala/ai/privado/exporter/ConsoleExporter.scala, src/main/scala/ai/privado/exporter/DataflowExporter.scala, src/main/scala/ai/privado/feeder/StorageInheritRule.scala, src/main/scala/ai/privado/model/Config.scala, src/main/scala/ai/privado/model/Constants.scala, src/main/scala/ai/privado/model/exporter/DataFlow.scala, src/main/scala/ai/privado/passes/config/PropertiesFilePass.scala, src/main/scala/ai/privado/rulevalidator/YamlFileValidator.scala, src/main/scala/ai/privado/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/tagger/config/DBConfigTagger.scala, src/main/scala/ai/privado/tagger/sink/CustomInheritTagger.scala, src/main/scala/ai/privado/tagger/sink/RegularSinkTagger.scala, src/main/scala/ai/privado/utility/Utilities.scala
1. Detect database type,name and location from configuration file ( proporty or yml )
2. Support to read .yml configuration file
3. Fix the code to detect PagingAndSortingRepository
=> feat: detect database type, name and location from config

build.sbt, src/main/scala/ai/privado/languageEngine/javascript/passes/methodfullname/MethodFullName.scala, src/main/scala/ai/privado/languageEngine/javascript/processor/JavascriptProcessor.scala
add - dependency upgrade to "1.1.1134"
patch - change `cpg.staticImports` to `cpg.imports`
=> patch - change createCpg to createCpgWithAllOverlays

src/main/scala/ai/privado/cache/AppCache.scala, src/main/scala/ai/privado/entrypoint/Main.scala, src/main/scala/ai/privado/exporter/ConsoleExporter.scala, src/main/scala/ai/privado/exporter/ExporterUtility.scala
fix - blank excerpt in docker image
fix - wrong repoName in privado.json for windows machine
patch - error message to inform user if something goes wrong in scan
=> fix - proper filename for getting dump in excerpt

build.sbt, project/SimpleCache.scala
Made changes with reference to
https://github.com/joernio/joern/pull/1805
=> Made changes to use updated version of astgen

src/main/scala/ai/privado/entrypoint/ScanProcessor.scala
=> fix - picking correct rule in case the repo has JavaScript as the main language

.github/workflows/comparison-results.yml
Removed retention days and modified the trigger metadata JSON file to support the updated dynamic comparison.
=> Comparison result generation

src/main/scala/ai/privado/languageEngine/java/processor/JavaProcessor.scala, src/main/scala/ai/privado/languageEngine/javascript/processor/JavascriptProcessor.scala, src/main/scala/ai/privado/languageEngine/python/processor/PythonProcessor.scala, src/main/scala/ai/privado/utility/UnresolvedReportUtility.scala
- Generate unresolved function report in .privado
- Generate report for java, js, python
=> Generate unresolved function report in .privado

src/main/scala/ai/privado/cache/AppCache.scala, src/main/scala/ai/privado/exporter/ExporterUtility.scala, src/main/scala/ai/privado/languageEngine/java/processor/JavaProcessor.scala, src/main/scala/ai/privado/model/Constants.scala
Fix - Empty excerpts for getter/setter in DTO
Fix - Excerpt mismatch w.r.t to sample on Dashboard
=> resolved conflict

src/main/scala/ai/privado/exporter/JSONExporter.scala, src/main/scala/ai/privado/model/exporter/DataFlow.scala
Changed the parameter name and create directory if not exist for intermediate result.
=> Refactoring parameter 

src/main/scala/ai/privado/languageEngine/java/processor/JavaProcessor.scala, src/main/scala/ai/privado/languageEngine/python/processor/PythonProcessor.scala
Export the unique flow json file for python when `--test-output` provided
=> Unique flow export for Python

.github/workflows/comparison-results.yml
Ticket: https://privado-ai.atlassian.net/browse/LE-178
=> Github action PR blocker

src/main/scala/ai/privado/languageEngine/java/tagger/sink/FeignAPI.scala, src/main/scala/ai/privado/languageEngine/java/tagger/sink/JavaAPITagger.scala, src/main/scala/ai/privado/tagger/utility/APITaggerUtility.scala
- Consider Member for API identifier Regex
- Consider Identifier Regex for Feign as well
=> add - consider members for identifier regex in API

.github/workflows/comparison-results.yml, .github/workflows/formatter.yml
Ticket: https://privado-ai.atlassian.net/browse/LE-229
=> Added formatter support

src/main/scala/ai/privado/dataflow/Dataflow.scala, src/main/scala/ai/privado/languageEngine/java/processor/JavaProcessor.scala, src/main/scala/ai/privado/languageEngine/java/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/languageEngine/java/tagger/source/IdentifierTagger.scala, src/main/scala/ai/privado/languageEngine/javascript/processor/JavascriptProcessor.scala, src/main/scala/ai/privado/languageEngine/python/processor/PythonProcessor.scala
2nd level derivation will work for Collection Point and Storages irrespective of 2nd level flag. - https://privado-ai.atlassian.net/browse/LE-55?atlOrigin=eyJpIjoiNzAzOGM4NWRhMTIzNDFiNmEwYWQyYmZmMTJjNTVlM2MiLCJwIjoiaiJ9
=> add - selective derivation for Collection point and storages

src/main/scala/ai/privado/dataflow/Dataflow.scala
Fixed the derived name issue in unique flow result. 
Ticket: https://privado-ai.atlassian.net/browse/LE-262
=> Unique Flow SourceId name fix

src/main/scala/ai/privado/languageEngine/java/tagger/sink/CustomInheritTagger.scala
https://privado-ai.atlassian.net/browse/LE-289?atlOrigin=eyJpIjoiZWQyYmExMTgwODIzNGNlZGI0NWY5YjIxYjBkZmFhZDgiLCJwIjoiaiJ9
=> fix - 2nd level derivation for storages

src/test/scala/ai/privado/languageEngine/python/passes/config/PythonPropertiesFilePassTest.scala
Bypassing few failing test for now
=> Python db config (#446)

.github/workflows/code-quality.yml
Added Unit Test check support in current workflow and if any of the unit tests fail, the entire workflow will stop.
Ticket: https://privado-ai.atlassian.net/browse/LE-293
=> Added unit test check support in workflow

src/main/scala/ai/privado/languageEngine/java/semantic/SemanticGenerator.scala, src/main/scala/ai/privado/languageEngine/java/tagger/source/IdentifierTagger.scala, src/main/scala/ai/privado/languageEngine/java/tagger/source/InSensitiveCallTagger.scala, src/main/scala/ai/privado/languageEngine/java/tagger/source/Utility.scala, src/main/scala/ai/privado/model/PrivadoTag.scala, src/test/scala/ai/privado/languageEngine/java/SemanticFirstLevelDerivationTest.scala, src/test/scala/ai/privado/languageEngine/java/SemanticSecondLevelDerivationTest.scala
https://privado-ai.atlassian.net/browse/LE-290?atlOrigin=eyJpIjoiNzM4MDJkNTYwMzNiNDBhY2FiMTdjNTgwMGY3M2M1YjQiLCJwIjoiaiJ9
=> Semantic for setter

.github/workflows/code-quality.yml, .github/workflows/comparison-results.yml
Changed workflow trigger branch to base branch.
Ticket: https://privado-ai.atlassian.net/browse/LE-316
=> Change workflow trigger branch

src/main/scala/ai/privado/languageEngine/python/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/tagger/sink/LogShareSinkTagger.scala
A complete code on how to integrate Sentry:
```
sentry_sdk.init(
dsn="https://xyz@abc.ingest.sentry.io/89635676",
traces_sample_rate=1.0
)
import logging
logging.error("I am an event", extra=dict(bar=43))
logging.exception("An exception happened")
```
Whenever error or exception log gets executed, a record will passed on sentry.io
We need to capture such statement if PII is going out from the system.
=> Support: Sentry python

src/main/scala/ai/privado/audit/AuditReportConstants.scala, src/main/scala/ai/privado/audit/DataElementDiscovery.scala, src/main/scala/ai/privado/exporter/ExcelExporter.scala, src/test/scala/ai/privado/languageEngine/java/audit/DataElementDiscoveryTest.scala, src/test/scala/ai/privado/languageEngine/java/audit/TestData/AuditTestClassData.scala
Added `File name`, `Member Type`, `Collection endpoint path`, `Collection method full name` in element discovery sheet. 
Ticket: https://privado-ai.atlassian.net/browse/LE-321
=> Added Additional column in audit discovery report

src/test/scala/ai/privado/languageEngine/java/passes/read/JavaSQLDatabaseReadTest.scala
Added collection Rule in the `JavaSQLDatabaseReadTest`
=> unit test collection rule fix

src/main/scala/ai/privado/languageEngine/java/passes/read/DatabaseReadPass.scala, src/main/scala/ai/privado/passes/SQLParser.scala, src/main/scala/ai/privado/utility/SQLParser.scala
- Add space to avoid concatenation of column after EOF
- Add SqlCleaner class to remove the comments
- Support Drop query parsing
- Support SetOperationList parsing
=> Fixes for the SQL Parser

build.sbt, src/main/scala/ai/privado/audit/AuditReportConstants.scala, src/main/scala/ai/privado/audit/AuditReportEntryPoint.scala, src/main/scala/ai/privado/audit/DataFlowReport.scala, src/main/scala/ai/privado/cache/AuditCache.scala, src/main/scala/ai/privado/cache/DataFlowCache.scala, src/main/scala/ai/privado/dataflow/Dataflow.scala, src/main/scala/ai/privado/dataflow/DuplicateFlowProcessor.scala, src/main/scala/ai/privado/languageEngine/java/processor/JavaProcessor.scala, src/main/scala/ai/privado/languageEngine/javascript/processor/JavascriptProcessor.scala, src/main/scala/ai/privado/languageEngine/python/passes/PrivadoPythonTypeHintCallLinker.scala, src/main/scala/ai/privado/languageEngine/python/processor/PythonProcessor.scala, src/test/scala/ai/privado/languageEngine/java/audit/DataFlowReportTest.scala, src/test/scala/ai/privado/languageEngine/java/audit/DataFlowReportTestBase.scala, src/test/scala/ai/privado/languageEngine/java/audit/TestData/AuditTestClassData.scala
Release: 24th April 2023:
1. Added Dataflow Sheet in Audit report
2. Added Hint Call Linker
=> Release: 24th April 2023: Dataflow Audit and Hint Call Linker

src/main/scala/ai/privado/passes/HTMLParserPass.scala
HtmlUnit library is not threadsafe. It in itself make use of multiple threads for processing single HTML file. Because we tried to use same instance across multiple threads. It is resulting into inconsistent outcome. Hence changed it to be instanciated for each thread separately.
Also added trace logs.
=> Fix for comparison report diff

src/main/scala/ai/privado/audit/DataFlowReport.scala, src/main/scala/ai/privado/cache/AuditCache.scala, src/main/scala/ai/privado/dataflow/Dataflow.scala, src/main/scala/ai/privado/entrypoint/CommandParser.scala, src/test/scala/ai/privado/languageEngine/java/audit/DataFlowReportTest.scala, src/test/scala/ai/privado/languageEngine/java/audit/TestData/AuditTestClassData.scala
Added Support to check the semantics filter in existing dataflow sheet present inside audit report. 
Ticket: https://privado-ai.atlassian.net/browse/LE-371
=> Added semantics filter check in dataflow sheet

build.sbt, src/test/scala/ai/privado/languageEngine/java/SemanticFirstLevelDerivationTest.scala, src/test/scala/ai/privado/languageEngine/java/SemanticSecondLevelDerivationTest.scala
Joern version update to 1.1.1699
=> Joern version upgrade to 1.1.1699

src/main/scala/ai/privado/audit/AuditReportConstants.scala, src/main/scala/ai/privado/audit/AuditReportEntryPoint.scala, src/main/scala/ai/privado/audit/UnresolvedFlowReport.scala, src/main/scala/ai/privado/cache/AuditCache.scala, src/main/scala/ai/privado/cache/DataFlowCache.scala, src/main/scala/ai/privado/dataflow/Dataflow.scala, src/main/scala/ai/privado/exporter/JSONExporter.scala, src/main/scala/ai/privado/languageEngine/java/processor/JavaProcessor.scala, src/main/scala/ai/privado/languageEngine/javascript/processor/JavascriptProcessor.scala, src/main/scala/ai/privado/languageEngine/python/processor/PythonProcessor.scala, src/main/scala/ai/privado/model/Constants.scala, src/test/scala/ai/privado/languageEngine/java/audit/TestData/AuditTestClassData.scala, src/test/scala/ai/privado/languageEngine/java/audit/UnresolvedFlowTest.scala, src/test/scala/ai/privado/languageEngine/java/audit/UnresolvedFlowTestBase.scala
Added unresolved-flow sheet into audit report. Also added support to export `unresolved-flow.json` when audit report flag provided.
=> Added audit unresolved flow sheet

build.sbt, src/main/resources/ai/privado/rulevalidator/schema/threats.json, src/main/scala/ai/privado/audit/AuditReportConstants.scala, src/main/scala/ai/privado/audit/AuditReportEntryPoint.scala, src/main/scala/ai/privado/audit/DataElementDiscovery.scala, src/main/scala/ai/privado/exporter/JSONExporter.scala, src/main/scala/ai/privado/languageEngine/java/processor/JavaProcessor.scala, src/main/scala/ai/privado/languageEngine/java/threatEngine/ThreatEngineExecutor.scala, src/main/scala/ai/privado/languageEngine/javascript/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/languageEngine/javascript/tagger/collection/CollectionTagger.scala, src/main/scala/ai/privado/languageEngine/javascript/tagger/source/IdentifierTagger.scala, src/main/scala/ai/privado/languageEngine/python/processor/PythonProcessor.scala, src/main/scala/ai/privado/metric/MetricHandler.scala, src/test/scala/ai/privado/languageEngine/java/SemanticFirstLevelDerivationTest.scala, src/test/scala/ai/privado/languageEngine/java/SemanticSecondLevelDerivationTest.scala, src/test/scala/ai/privado/languageEngine/java/audit/DataElementDiscoveryTest.scala, src/test/scala/ai/privado/languageEngine/javascript/tagger/sinks/collection/CollectionTaggerTest.scala
* Added Python's `DynamicTypeHintFullNamePass` 
* Using new semantic API where `ParamMapping` becomes `FlowMapping`
=> Added DynamicTypeHintFullNamePass & Fixed Old Semantic API

src/main/scala/ai/privado/languageEngine/javascript/tagger/collection/CollectionTagger.scala, src/main/scala/ai/privado/languageEngine/javascript/tagger/source/IdentifierTagger.scala
- [Use pattern from Collection Express rule](https://github.com/Privado-Inc/privado-core/commit/804ba1e303ca2b26f3a6cda6eceaa9bb23dcae71)
- [Remove FPs from import/require statements](https://github.com/Privado-Inc/privado-core/commit/b694bef93626879c954270783fea704208a789cd)
- [Add support for parsing block with method, path & handler for Collection](https://github.com/Privado-Inc/privado-core/commit/cdcb58cd9fb16544b676809beeeb3248c32e96cf)
=> Js fixes 2

src/main/scala/ai/privado/languageEngine/javascript/passes/config/JSPropertyLinkerPass.scala, src/main/scala/ai/privado/languageEngine/javascript/tagger/collection/CollectionTagger.scala, src/main/scala/ai/privado/languageEngine/javascript/tagger/source/IdentifierTagger.scala
- Fix the JS property not getting populated in API flows
- Use pattern from Collection Express rule
- Remove FPs from import/require statements
- Add support for parsing block with method, path & handler for Collection
=> Javascript fixes

src/main/scala/ai/privado/audit/AuditReportConstants.scala, src/main/scala/ai/privado/audit/AuditReportEntryPoint.scala, src/main/scala/ai/privado/audit/DataElementDiscovery.scala, src/main/scala/ai/privado/audit/DependencyReport.scala, src/main/scala/ai/privado/languageEngine/javascript/processor/JavascriptProcessor.scala, src/main/scala/ai/privado/languageEngine/python/processor/PythonProcessor.scala
* basic support for audit report JS
* minor refactoring
=> basic support for audit report JS (#629)

.idea/codeStyles/Project.xml, build.sbt, updateDependencies.sh
* Updated privado language engine version to 2.0.13
* Removed unnecessary files
* remove unnecessary file
* change updateDependencies.sh to use scala 3
* Update underlying dependencies
=> Language engine/version update (#640)

src/main/scala/ai/privado/exporter/ProbableSinkExporter.scala, src/main/scala/ai/privado/languageEngine/ruby/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/languageEngine/ruby/tagger/sink/APITagger.scala, src/main/scala/ai/privado/utility/Utilities.scala, src/test/scala/ai/privado/exporter/ProbableSinkExporterTest.scala, src/test/scala/ai/privado/utility/UtilitiesTest.scala
- Adding support for Ruby API Tagger
- Adding support for Probable Sinks for Ruby
=> Ruby: Add support for API Tagger + Probable Sinks

src/main/scala/ai/privado/languageEngine/ruby/feeder/StorageInheritRule.scala, src/main/scala/ai/privado/languageEngine/ruby/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/languageEngine/ruby/tagger/sink/InheritMethodTagger.scala
Added ruby inheritMethod pass and Storage inherit rule.
=> Added Ruby Inherit method pass

src/main/scala/ai/privado/entrypoint/ScanProcessor.scala
This PR contains changes required for merging rule patterns for duplicate SourceIds
=> merging rule patterns for sources

src/main/scala/ai/privado/audit/AuditReportConstants.scala, src/main/scala/ai/privado/audit/DataElementDiscovery.scala, src/main/scala/ai/privado/entrypoint/ScanProcessor.scala
This PR contains changes done to assign file priority score for the Java Script repos, 
Added a function getFileScoreJS for the Implementation of the same.
=> Added file priority logic for JS repos

src/main/scala/ai/privado/languageEngine/ruby/processor/RubyProcessor.scala
Reverts Privado-Inc/privado-core#674
=> Revert "Ruby post processing pass"

Dockerfile
=> ruby: added ruby dependency

src/main/scala/ai/privado/languageEngine/ruby/tagger/sink/RegularSinkTagger.scala
Added dynamicTypeHintName for sink tagging
=> DynamicTypeHintFullName for sink tagging

src/main/scala/ai/privado/languageEngine/ruby/passes/GlobalImportPass.scala, src/main/scala/ai/privado/languageEngine/ruby/passes/RubyExternalTypesPass.scala, src/main/scala/ai/privado/languageEngine/ruby/passes/download/DownloadDependenciesPass.scala, src/main/scala/ai/privado/languageEngine/ruby/processor/RubyProcessor.scala, src/main/scala/ai/privado/languageEngine/ruby/tagger/sink/APITagger.scala, src/main/scala/ai/privado/utility/ConcurrentProcessor.scala
The PR helps in getting cleaner Sinks (Sinks with less FP's and more coverage)
=> [WIP] Ruby types

README.md, src/main/scala/ai/privado/entrypoint/ScanProcessor.scala, src/main/scala/ai/privado/languageEngine/default/processor/DefaultProcessor.scala, src/main/scala/ai/privado/languageEngine/default/semantic/Language.scala, src/main/scala/ai/privado/languageEngine/default/tagger/PrivadoTagger.scala
* add default processor for unkown language
* fixing compile errors
* trigger
---------
=> Default processor for unsupported languages (#703)

build.sbt
=> Downgrade LanguageEngine version as the new version is getting stuck in some ruby files

src/main/scala/ai/privado/languageEngine/javascript/tagger/sink/JSAPITagger.scala
* Add support for detecting scripts from loadexternal script method
=> JS: Add support for detecting scripts from loadexternal script method

src/main/scala/ai/privado/exporter/JSONExporter.scala
* possible fix for export utility
* refactor
* error handling
=> Fix: Parallel processing in JSON export. (#720)

src/main/scala/ai/privado/languageEngine/go/tagger/PrivadoTagger.scala
Added taggers which are common across language:
1. SqlQueryTagger
2. RegularSinkTagger
=> Go: added additional  tagger

src/main/scala/ai/privado/cache/RuleCache.scala, src/main/scala/ai/privado/passes/PropertyParserPass.scala
The PR fixes the following
- Rules getting processed twice
- Too many property nodes getting generated via propertyPass
=> fix - rules getting added twice

src/main/scala/ai/privado/audit/DataElementDiscovery.scala
This PR contains logic to remove duplicates members, identifiers, locals which were still visible in previous PR of Remove duplicates
=> feat: refractor changes

build.sbt, src/main/scala/ai/privado/languageEngine/ruby/passes/download/DownloadDependenciesPass.scala, src/main/scala/ai/privado/languageEngine/ruby/processor/RubyProcessor.scala, src/main/scala/ai/privado/model/Constants.scala, src/main/scala/ai/privado/utility/ConcurrentProcessor.scala, src/test/scala/ai/privado/languageEngine/ruby/download/ExternalDependenciesDownloadTest.scala, src/test/scala/ai/privado/utility/ConcurrentProcessorTest.scala
Fixes download dependency issue we sometimes face with large dependency list
=> increase zeromq sockets

build.sbt, src/main/scala/ai/privado/languageEngine/go/tagger/config/GoDBConfigTagger.scala
Sample property getting tagged due to change:
```mongodb://myusername:mypassword@localhost:27017/mydatabase?ssl=true```
```postgresql://myuser:mypassword@10.0.0.1:5432/mydatabase```
=> Go: Property Tagger

.github/workflows/comparison-results.yml
Use a language-wise parallel workflow for the comparison report.
=> Parallel workflow for comparison report

src/main/scala/ai/privado/languageEngine/go/processor/GoProcessor.scala
exclude file regex defined in go exclusion rule
=> [Go] Support for regex exclude file

.github/workflows/privado-language-engine-version.yml
@pandurangpatil, please review.
=> [Feat] Language engine comparison on github actions

src/main/scala/ai/privado/exporter/JSONExporter.scala, src/main/scala/ai/privado/exporter/PolicyAndThreatExporter.scala, src/main/scala/ai/privado/languageEngine/java/threatEngine/CustomPrivacyLoggerMustbeUsed.scala, src/main/scala/ai/privado/languageEngine/java/threatEngine/DataMethodParameterHardcoded.scala, src/main/scala/ai/privado/languageEngine/java/threatEngine/DifferentKindOfPIIStoredInDifferentTables.scala, src/main/scala/ai/privado/languageEngine/java/threatEngine/ObjectsWithPIIsPassedAsParameter.scala, src/main/scala/ai/privado/languageEngine/java/threatEngine/PIIHavingDifferentRetentionPeriod.scala, src/main/scala/ai/privado/languageEngine/java/threatEngine/PIIShouldNotBePresentInMultipleTables.scala, src/main/scala/ai/privado/languageEngine/java/threatEngine/ThreatUtility.scala, src/main/scala/ai/privado/model/exporter/Violation.scala, src/main/scala/ai/privado/policyEngine/PolicyExecutor.scala
On the customer repo, we observed a weird bug while exporting, while debugging found it was introduced due to the PR - https://github.com/Privado-Inc/privado-core/pull/579
Have done some refactoring so that the code follows more stands of scala
cc - @pandurangpatil
=> Fix - Bug in export

src/main/scala/ai/privado/exporter/PolicyAndThreatExporter.scala, src/main/scala/ai/privado/languageEngine/java/threatEngine/CustomPrivacyLoggerMustbeUsed.scala, src/main/scala/ai/privado/languageEngine/java/threatEngine/DataMethodParameterHardcoded.scala, src/main/scala/ai/privado/languageEngine/java/threatEngine/DifferentKindOfPIIStoredInDifferentTables.scala, src/main/scala/ai/privado/languageEngine/java/threatEngine/ObjectsWithPIIsPassedAsParameter.scala, src/main/scala/ai/privado/languageEngine/java/threatEngine/PIIHavingDifferentRetentionPeriod.scala, src/main/scala/ai/privado/languageEngine/java/threatEngine/PIIShouldNotBePresentInMultipleTables.scala, src/main/scala/ai/privado/languageEngine/java/threatEngine/ThreatUtility.scala, src/main/scala/ai/privado/model/exporter/Violation.scala, src/main/scala/ai/privado/policyEngine/PolicyExecutor.scala
* fix - error while exporting on some repos
* fix and refactoring
=> Fix - Bug in export (#781)

build.sbt, src/main/scala/ai/privado/languageEngine/ruby/passes/GlobalImportPass.scala, src/main/scala/ai/privado/languageEngine/ruby/passes/PrivadoRubyTypeRecoveryPass.scala, src/main/scala/ai/privado/languageEngine/ruby/passes/RubyExternalTypesPass.scala, src/main/scala/ai/privado/languageEngine/ruby/passes/RubyImportResolverPass.scala, src/main/scala/ai/privado/languageEngine/ruby/passes/download/DownloadDependenciesPass.scala, src/main/scala/ai/privado/languageEngine/ruby/processor/RubyProcessor.scala, src/test/scala/ai/privado/languageEngine/ruby/config/RubyPropertiesFilePassTestBase.scala, src/test/scala/ai/privado/languageEngine/ruby/download/ExternalDependenciesDownloadTest.scala
Adapting our core to use the `deprecated` package for the existing ruby frontend based on recent changes upstream: https://github.com/joernio/joern/pull/3755 This was tested on a few ruby repos like `pay` and `olubalance`
=> Update for ruby package change

build.sbt, src/main/scala/ai/privado/languageEngine/ruby/processor/RubyProcessor.scala
Upgrade core engine version to 140(https://github.com/Privado-Inc/privado-core/commit/e12528337765f6eccc19d2335eba63124db606d9)
=> Upgrade core engine version to 140

src/main/scala/ai/privado/languageEngine/java/tagger/source/IdentifierTagger.scala, src/main/scala/ai/privado/languageEngine/java/tagger/source/InSensitiveCallTagger.scala, src/main/scala/ai/privado/languageEngine/java/tagger/source/Utility.scala
This PR is extension to - https://github.com/Privado-Inc/privado-core/pull/827
=> use caching for field access

src/main/scala/ai/privado/cache/RuleCache.scala, src/main/scala/ai/privado/languageEngine/go/processor/GoProcessor.scala, src/main/scala/ai/privado/languageEngine/ruby/processor/RubyProcessor.scala
Revert change for `ruby` and `golang`
=> [Gosrc2cpg] Go exclusion fix

src/main/scala/ai/privado/exporter/CollectionExporter.scala, src/main/scala/ai/privado/languageEngine/java/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/languageEngine/kotlin/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/tagger/collection/AndroidCollectionTagger.scala, src/test/scala/ai/privado/passes/AndroidXmlPassTest.scala
* add android xml field identifiers to collection exporter
* move android collection tagger outside of kotlin
* enable android collection tagging for java
=> Collection exporter fix and refactor

src/main/scala/ai/privado/languageEngine/go/passes/orm/ORMParserPass.scala, src/test/scala/ai/privado/languageEngine/go/passes/orm/ORMParserTest.scala
replaced the `[]` and `*` present in typeFullName with empty char to construct the valid regex.
=> [gosrc2cpg] - ORMParserPass regex issue fix

build.sbt, src/test/scala/ai/privado/script/ExternalScalaScriptTest.scala
* fix - aws codebuild timeout issue
* formatting
=> fix - aws codebuild timeout issue (#854)

build.sbt, src/main/scala/ai/privado/languageEngine/python/processor/PythonProcessor.scala, src/main/scala/ai/privado/languageEngine/ruby/passes/PrivadoRubyTypeRecoveryPassGenerator.scala, src/main/scala/ai/privado/languageEngine/ruby/processor/RubyProcessor.scala, src/test/scala/ai/privado/languageEngine/go/GoTestBase.scala, src/test/scala/ai/privado/languageEngine/python/PrivadoPySrc2CpgFixture.scala, src/test/scala/ai/privado/languageEngine/python/PythonTestUtility.scala, src/test/scala/ai/privado/languageEngine/python/passes/config/PythonPropertiesFilePassTest.scala
See https://github.com/joernio/joern/pull/3886
=> [API] Accommodating Type Recovery Changes

build.sbt
the change is expected with joern changes, hence reverting the change.
=> the change is expected with joern changes

README.md, build.sbt, src/test/scala/ai/privado/languageEngine/go/GoTestBase.scala, src/test/scala/ai/privado/languageEngine/go/tagger/sink/GoAPITaggerTest.scala
* apihttplibraries improvement
* SOAP Api unit test added
=> [Gosrc2cpg] - apihttplibraries improvement (#871)

src/main/scala/ai/privado/exporter/CollectionExporter.scala, src/main/scala/ai/privado/languageEngine/ruby/tagger/monolith/MonolithTagger.scala
This PR adds monolith subProject support for graphQL
=> Monolith add support for graphql subProjects

.gitignore, build.sbt, log4j2.xml, src/main/scala/ai/privado/exporter/CollectionExporter.scala, src/main/scala/ai/privado/languageEngine/ruby/tagger/monolith/MonolithTagger.scala
* le version upgrade
* version update with fixes
=> le version upgrade (#880)

src/main/scala/ai/privado/audit/AuditReportEntryPoint.scala
For some reason, import removed in this PR is throwing build error on Linux machine with JDK 18. As it was unwanted, I have removed the same.
=> Unwanted import removal.

src/main/scala/ai/privado/languageEngine/ruby/passes/PrivadoRubyTypeRecoveryPassGenerator.scala, src/test/scala/ai/privado/languageEngine/ruby/RubyTestBase.scala, src/test/scala/ai/privado/languageEngine/ruby/passes/MethodFullNameForExternalNodesTest.scala, src/test/scala/ai/privado/languageEngine/ruby/passes/MethodFullNameForInternalNodesTest.scala, src/test/scala/ai/privado/languageEngine/ruby/passes/SchemaParserTest.scala
- Added exception handling for methodReturn query
- Add a test case for external dependency download and resolution in ruby
- TypeRecovery cleanup on redundant methods
=> added exception handling for methodReturn query

src/main/scala/ai/privado/languageEngine/java/processor/JavaProcessor.scala
For debugging the lombok issue in java, we are not deleting the generated lombok code, to try out different things on top of it
=> try debug lombok

src/main/scala/ai/privado/exporter/ExporterUtility.scala
1. Made changes to move writing to output collection from inside future to main thread.
2. Added few debug logs to understand if any future is getting stuck.
=> Removed the dead lock possibility

src/main/scala/ai/privado/exporter/ExporterUtility.scala
1. Made changes to move writing to output collection from inside future to main thread.
2. Added few debug logs to understand if any future is getting stuck.
=> Removed the dead lock possibility (#934)

schema/src/main/scala/CpgExtSchema.scala, src/main/scala/ai/privado/entrypoint/ScanProcessor.scala, src/main/scala/ai/privado/languageEngine/javascript/passes/config/JSPropertyLinkerPass.scala, src/main/scala/ai/privado/languageEngine/javascript/passes/config/JsConfigPropertyPass.scala, src/main/scala/ai/privado/languageEngine/javascript/processor/JavascriptProcessor.scala, src/main/scala/ai/privado/languageEngine/python/config/PythonConfigPropertyPass.scala, src/main/scala/ai/privado/languageEngine/python/passes/config/PythonPropertyLinkerPass.scala, src/main/scala/ai/privado/languageEngine/python/processor/PythonProcessor.scala, src/main/scala/ai/privado/model/PrivadoTag.scala, src/test/scala/ai/privado/languageEngine/javascript/passes/config/JsConfigPropertyPassTest.scala, src/test/scala/ai/privado/languageEngine/python/passes/config/PythonConfigPropertyPassTest.scala
As properties can be defined in .js, .py file, this PR focusses on creating nodes for them
=> add - support for reading creating property nodes from .js, .py file

src/test/scala/ai/privado/languageEngine/java/passes/config/PropertiesFilePassTest.scala
=> Egress: ignored failing test case

src/main/scala/ai/privado/entrypoint/ScanProcessor.scala, src/main/scala/ai/privado/exporter/ExporterUtility.scala, src/main/scala/ai/privado/languageEngine/java/processor/JavaProcessor.scala, src/main/scala/ai/privado/languageEngine/javascript/processor/JavascriptProcessor.scala, src/main/scala/ai/privado/languageEngine/kotlin/processor/KotlinProcessor.scala, src/main/scala/ai/privado/languageEngine/python/processor/PythonProcessor.scala, src/main/scala/ai/privado/languageEngine/ruby/processor/RubyProcessor.scala, src/main/scala/ai/privado/model/Constants.scala, src/main/scala/ai/privado/passes/JsonPropertyParserPass.scala
* generate property nodes from generated jsons
* scan property from .privado/config folder
* fix - json parser bug
=> Add/asset discovery on generated json (#952)

src/main/scala/ai/privado/exporter/CollectionExporter.scala, src/main/scala/ai/privado/languageEngine/javascript/tagger/collection/CollectionTagger.scala, src/test/scala/ai/privado/languageEngine/javascript/tagger/collection/CollectionTaggerTest.scala, src/test/scala/ai/privado/policyEngine/PolicyTests.scala
* add - support for more case in express
* fix failing test case
=> add - support for more case in express (#962)

src/main/scala/ai/privado/exporter/ExporterUtility.scala, src/main/scala/ai/privado/passes/JsonPropertyParserPass.scala
* improve regex
* read all files in generated config
* remove package.json
* PR comment
=> improve regex (#966)

build.sbt, src/main/scala/ai/privado/exporter/ExporterUtility.scala, src/main/scala/ai/privado/languageEngine/java/feeder/StorageInheritRule.scala, src/main/scala/ai/privado/model/exporter/Asset.scala
* improve regex
* read all files in generated config
* remove package.json
* PR comment
* improve regex
=> Improve asset regex (#970)

src/main/scala/ai/privado/languageEngine/java/processor/JavaProcessor.scala
PR fixes the following
- The check to delete `delombok` folder once scan is completed was commented out earlier while testing, which was released. Have uncommented that now, this fixes the deletion of delombok code once scan is completed succesfully
- Earlier we were creating a `delombok` directory and then invoking the delombok generator which was generating 2 delombok folder. Have removed the logic to create a `delombok` directory ourself. This fixes the creation of 2 delombok folder instead of the expected 1 folder
=> fix - lombok folder deletion

src/main/scala/ai/privado/languageEngine/ruby/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/languageEngine/ruby/tagger/sink/RegularSinkTagger.scala, src/main/scala/ai/privado/languageEngine/ruby/tagger/source/IdentifierDerivedTagger.scala, src/main/scala/ai/privado/languageEngine/ruby/tagger/source/RubyLiteralTagger.scala, src/test/scala/ai/privado/languageEngine/ruby/passes/SchemaParserTest.scala
* add more sources in ruby
* more test case
=> add more sources in ruby (#980)

src/main/scala/ai/privado/entrypoint/ScanProcessor.scala, src/main/scala/ai/privado/languageEngine/php/processor/PhpProcessor.scala, src/main/scala/ai/privado/languageEngine/php/semantic/Language.scala, src/main/scala/ai/privado/languageEngine/php/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/languageEngine/ruby/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/model/PrivadoTag.scala, src/main/scala/ai/privado/tagger/source/IdentifierTagger.scala
This PR checks in the processor for `PHP` as part of support for `PHP` language.
=> Add support for PHP

src/main/scala/ai/privado/exporter/SourceExporter.scala
Show derived sources in processing for monolith project
=> show derived sources in processing for monolith project

build.sbt
The production build works fine, `sbt clean stage` fails.
=> Fix stage error for `DotNetAstGen`

.gitignore, src/main/scala/ai/privado/exporter/HttpConnectionMetadataExporter.scala, src/test/scala/ai/privado/exporter/PythonLanguageEgressTest.scala
=> fix(languageEgress): consider a string which has slash in the end

.gitignore, build.sbt, src/main/scala/ai/privado/exporter/HttpConnectionMetadataExporter.scala, src/main/scala/ai/privado/languageEngine/python/processor/PythonProcessor.scala, src/test/scala/ai/privado/exporter/PythonLanguageEgressTest.scala, src/test/scala/ai/privado/languageEngine/python/PythonS3TaggerTest.scala, src/test/scala/ai/privado/languageEngine/python/PythonTestUtility.scala
* upgrade le version, and fix build errors
* fix test errors
=> Upgrade LE version, and fix build errors (#1005)

src/main/scala/ai/privado/languageEngine/go/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/languageEngine/java/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/languageEngine/java/tagger/collection/MethodFullNameCollectionTagger.scala, src/main/scala/ai/privado/languageEngine/javascript/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/languageEngine/kotlin/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/languageEngine/python/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/languageEngine/ruby/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/utility/Utilities.scala, src/test/scala/ai/privado/languageEngine/java/tagger/collection/CollectionUtilityTest.scala
* Fix ingressUrls collection during method full name tagging.
* Make the ingressUrls into a list buffer.
=> LE-1096 | Fix ingressUrls append for method full name collection tagger

src/main/scala/ai/privado/exporter/ExporterUtility.scala, src/main/scala/ai/privado/exporter/RepoConfigMetaDataExporter.scala, src/main/scala/ai/privado/model/Constants.scala, src/test/scala/ai/privado/exporter/RepoConfigMetadataExporterTest.scala
Added Support to export the repo config metadata that fetch it from property files.
=> Repo Config Metadata Support

src/main/scala/ai/privado/passes/SQLParser.scala, src/main/scala/ai/privado/utility/SQLParser.scala, src/test/scala/ai/privado/passes/SQLParserTest.scala
* fix SQL lineNumber when query is found in .sql file
* use query start lineNumber instead of table lineNumber, and more tests
=> Release PR

src/main/scala/ai/privado/exporter/RepoConfigMetaDataExporter.scala, src/main/scala/ai/privado/model/Constants.scala, src/test/scala/ai/privado/exporter/RepoConfigMetadataExporterTest.scala
Added filePath field in newly added repo config info. So if any property name matches with given regex, now we will output `name`, `value`, `filePath`.
=> Repo Config FilePath

src/main/scala/ai/privado/languageEngine/java/tagger/sink/api/Utility.scala
- When looking for parameter/identifier which match the `apiIdentifier` regex, we pick only the 1st match, as picking all with result in overtagging the API Sink
- Before matching on parameter name, match on the `@Named` annotation, if it contains a url like value use that to tag API
=> added more comments

src/main/scala/ai/privado/cache/AppCache.scala
fixed the repoName string in AppCache.
=> Repo Name output fix

build.sbt, src/test/scala/ai/privado/languageEngine/java/audit/DataElementDiscoveryTestBase.scala
Fixed the delombok issue that introduced after [this](https://github.com/joernio/joern/pull/4358/commits/c5bf4822b3026733234533451734d51d91769559) change.
=> core engine upgrade 2.0.311

build.sbt, src/main/scala/ai/privado/languageEngine/csharp/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/languageEngine/csharp/tagger/collection/CollectionTagger.scala, src/test/scala/ai/privado/languageEngine/csharp/CSharpTestBase.scala, src/test/scala/ai/privado/languageEngine/csharp/tagger/collection/CollectionTaggerTest.scala
* Adds basic collections support for AspNetCore MVC style routing
* Supports Attribute Routing and not Conventional Routing
* Ref: https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/routing
=> csharp: add collections support

src/main/scala/ai/privado/languageEngine/php/tagger/source/IdentifierTagger.scala
The long-term and best solution is to handle AST-related anomalies either when constructing the AST or by introducing an additional pass. This PR is more of a short-term solution as discussed within the team.
=> Wrap PHP entity tagging using `Try`

src/main/scala/ai/privado/dataflow/Dataflow.scala, src/main/scala/ai/privado/exporter/AndroidPermissionsExporter.scala, src/main/scala/ai/privado/exporter/CollectionExporter.scala, src/main/scala/ai/privado/exporter/DataflowExporter.scala, src/main/scala/ai/privado/exporter/ExporterUtility.scala, src/main/scala/ai/privado/exporter/PolicyAndThreatExporter.scala, src/main/scala/ai/privado/exporter/SinkExporter.scala, src/main/scala/ai/privado/exporter/SourceExporter.scala, src/main/scala/ai/privado/model/Constants.scala, src/main/scala/ai/privado/policyEngine/PolicyExecutor.scala, src/main/scala/ai/privado/threatEngine/CustomPrivacyLoggerMustbeUsed.scala, src/main/scala/ai/privado/threatEngine/DataMethodParameterHardcoded.scala, src/main/scala/ai/privado/threatEngine/DataOnExternalStorage.scala, src/main/scala/ai/privado/threatEngine/DifferentKindOfPIIStoredInDifferentTables.scala, src/main/scala/ai/privado/threatEngine/DifferentKindOfPIIStoredInDifferentTablesWithSQL.scala, src/main/scala/ai/privado/threatEngine/ObjectsWithPIIsPassedAsParameter.scala, src/main/scala/ai/privado/threatEngine/PIIHavingDifferentRetentionPeriod.scala, src/main/scala/ai/privado/threatEngine/PIIHavingDifferentRetentionPeriodWithSQL.scala, src/main/scala/ai/privado/threatEngine/PIIShouldNotBePresentInMultipleTables.scala, src/main/scala/ai/privado/threatEngine/PIIShouldNotBePresentInMultipleTablesWithSQL.scala, src/main/scala/ai/privado/threatEngine/ThreatEngineExecutor.scala, src/main/scala/ai/privado/threatEngine/ThreatUtility.scala, src/main/scala/ai/privado/utility/Utilities.scala, src/test/scala/ai/privado/exporter/ExportUtilityTest.scala, src/test/scala/ai/privado/languageEngine/java/audit/UnresolvedFlowTest.scala, src/test/scala/ai/privado/testfixtures/JavaFrontendTestSuite.scala, src/test/scala/ai/privado/testfixtures/LanguageFrontend.scala
This PR limits the lines added to code snippets to ensure that lengthy code is truncated, allowing the browser to render the code without getting stuck
=> Code Character Limiter

build.sbt, src/main/scala/ai/privado/languageEngine/javascript/tagger/source/IdentifierTagger.scala
We need to do a deep analysis into when to use `possibleTypes` and `typeFullName`, `methodFullName`, `dynamicTypeHintFullName` etc
We may also need to make changes in audit report or any other place if we see a gap
=> use possibleTypes in identifierTagger of JS

build.sbt
This reverts commit dc84418604fd2d2c190cbe64ff297ce30ee1ad0a.
=> Revert "Update build.sbt"

custom-build/Dockerfile, custom-build/custom_build.sh, src/main/scala/ai/privado/exporter/ExporterUtility.scala, src/main/scala/ai/privado/languageEngine/javascript/tagger/sink/RegularSinkTagger.scala, src/main/scala/ai/privado/model/Constants.scala, src/main/scala/ai/privado/model/exporter/DataFlow.scala, src/main/scala/ai/privado/tagger/collection/AndroidCollectionTagger.scala, src/main/scala/ai/privado/tagger/sink/SinkArgumentUtility.scala, src/main/scala/ai/privado/utility/Utilities.scala, src/test/scala/ai/privado/tagger/sink/SinkArgumentUtilityTest.scala
- [Support of arguments in GTM & Segment sinks](https://github.com/Privado-Inc/privado-core/commit/e263e54871695dd080d890cbec9f7d0b2a7fd959)
- custom build support
=> Support of arguments in GTM & Segment sinks

src/main/scala/ai/privado/languageEngine/python/tagger/sink/AirflowOperatorSinkPass.scala
After creating the custom rule for operators, need to add rules into `RuleCache` so that when generating the `privado.json`  rule gets resolved.
=> Airflow UI blank issue fix

build.sbt, src/main/scala/ai/privado/dataflow/Dataflow.scala, src/main/scala/ai/privado/languageEngine/default/passes/HighTouchPass.scala, src/main/scala/ai/privado/languageEngine/default/passes/PropertyVerificationPass.scala, src/main/scala/ai/privado/languageEngine/default/processor/DefaultProcessor.scala, src/main/scala/ai/privado/utility/SQLParser.scala
* merge
* parse hightouch repository using default processor and tag sources, and sinks
* minor refactors
* more logs
* dummy commit
* dataflow support for hightouch
* fix line numbers in sql, and populate code in hightouch sinks
* add tests for line numbers in sql
* upgrade sql parser lib version, fix sql parsing issues, added logs, and property nodes for yml files
* add a property verification pass for logs
* scalafmt
=> Enhance HighTouch support (#1105)

build.sbt
=> Dependency upgrade (#1120)

src/main/scala/ai/privado/entrypoint/CommandParser.scala, src/main/scala/ai/privado/entrypoint/Main.scala, src/main/scala/ai/privado/utility/StatsRecorder.scala
Added thread dump after regular interval of time default to 10 mins and if the avg cpu utilisation is lower than the 50% for given stage.
=> Added thread dump after regular interval of time

src/main/scala/ai/privado/passes/SQLParser.scala, src/main/scala/ai/privado/utility/SQLParser.scala
Remove unnecessary error logs, and print statements which pollutes console output.
=> Minor refactors

src/main/scala/ai/privado/entrypoint/Main.scala, src/main/scala/ai/privado/exporter/ExporterUtility.scala, src/main/scala/ai/privado/threatEngine/ThreatUtility.scala, src/main/scala/ai/privado/utility/Utilities.scala
These will be reverted once the actual root cause is fixed. 
Ticket for the fix: https://privado-ai.atlassian.net/jira/software/c/projects/LE/boards/8?assignee=637b03a85fc160544e1898c4&selectedIssue=LE-1384
=> Increment lineNumber if file is .cs

src/main/scala/ai/privado/entrypoint/DynamicRuleMerger.scala, src/main/scala/ai/privado/entrypoint/RuleProcessor.scala, src/test/scala/ai/privado/entrypoint/DynamicRuleMergerTest.scala
Dynamic rule create by 3ps discovery will be merged with existing rule with defined logic.
=> Dynamic rule merging
