Privado-Inc/privado-core

log4j2.xml, src/main/scala/ai/privado/dataflow/DuplicateFlowProcessor.scala, src/main/scala/ai/privado/entrypoint/ScanProcessor.scala, src/main/scala/ai/privado/java/exporter/ExporterUtility.scala, src/main/scala/ai/privado/java/exporter/SourceExporter.scala, src/main/scala/ai/privado/java/processor/Processor.scala, src/main/scala/ai/privado/model/PrivadoTag.scala, src/main/scala/ai/privado/rulevalidator/YamlFileValidator.scala, src/main/scala/ai/privado/utility/Utilities.scala
- Process only language specific rules. (Make use of the `language.yaml`)
Ex - If scanning for `javascript`, `java` rules should not be considered
- Cache relevant rules only
=> add - processing language specific rule

src/main/scala/ai/privado/javascript/passes/methodfullname/MethodFullName.scala, src/main/scala/ai/privado/javascript/passes/methodfullname/MethodFullNameFromIdentifier.scala, src/main/scala/ai/privado/javascript/tagger/sink/RegularSinkTagger.scala, src/main/scala/ai/privado/tagger/sink/RegularSinkTagger.scala
add - support for  `const {WebClient}  = require('@slack/web-api')`
add - support for adding methodFullName in chaining via fieldAccess - Ex- `web.chat.postMessage()`
=> Support for curly brace imports

build.sbt
Jackson core issue: 
`com.networknt json-schema-validator` is using jackson-version `2.14.0`, causing issues with the other libraries. Upgrading version to 2.14.0 for fix.
=> patch: update jackson-core version

sampletestrules/config/sinkskiplist/java.yaml, src/main/resources/ai/privado/rulevalidator/schema/sinkSkipList.json, src/main/scala/ai/privado/cache/RuleCache.scala, src/main/scala/ai/privado/entrypoint/CommandParser.scala, src/main/scala/ai/privado/entrypoint/ScanProcessor.scala, src/main/scala/ai/privado/exporter/JSONExporter.scala, src/main/scala/ai/privado/exporter/SinkExporter.scala, src/main/scala/ai/privado/model/Config.scala, src/main/scala/ai/privado/model/Constants.scala, src/main/scala/ai/privado/model/PrivadoTag.scala, src/main/scala/ai/privado/rulevalidator/YamlFileValidator.scala, src/main/scala/ai/privado/utility/Utilities.scala
- Currently we have limited set of rules written for Third Parties & Databases.
- So, after scanning it may be case that some Third Party is present but not detected via tool as rule missing.
- We will be exporting all the external packages in **probableSinks** key in privado.json
=> Export the probable sinks to privado.json file

src/main/scala/ai/privado/exporter/ExporterUtility.scala, src/main/scala/ai/privado/languageEngine/java/threatEngine/ThreatUtility.scala, src/main/scala/ai/privado/utility/Utilities.scala
We added functionality to show the type of the sample which getting highlighted in the code snippet.
=> Add sample types in snippet highlighted line

src/main/scala/ai/privado/dataflow/DuplicateFlowProcessor.scala, src/main/scala/ai/privado/tagger/utility/APITaggerUtility.scala
Solving the problem were `slackWebHookUrl` point to the URL `hooks.slack.com` and we show 2 API's
The flow of slackWebHookUrl is a sub-flow of the flow starting from hooks.slack.com and hence will be discarded by deduplication logic
=> fix - dedup on api flows

src/main/scala/ai/privado/cache/AppCache.scala, src/main/scala/ai/privado/dataflow/Dataflow.scala, src/main/scala/ai/privado/dataflow/DuplicateFlowProcessor.scala, src/main/scala/ai/privado/entrypoint/ScanProcessor.scala
- Caching the language the repo contains, so that we can use the cache latter
- Adding a condition, so that the FP flags `disable-this-filtering` and `disable-segregation-by-dataelement` is only done for JAVA language, and it doesn't filter out flows in other Languages
=> segregation of FP flag between language

src/main/scala/ai/privado/languageEngine/javascript/passes/methodfullname/MethodFullNameForEmptyNodes.scala
Method full have resolution for JS is 65-70% through Joern. Passes have been out in `privado-core `to add more resolution. 
For nodes with methodFullName being `<unknownFullName>`, no method fullname gets generated/substituted causing regex for sink to not match. This results in sinks not being identified.
This change converts `<unknownFullName>` to `<unknownFullName>.functionName()` to allow regex matching on `functionName`
=> LE-260: Javascript methodFullName hack

src/main/scala/ai/privado/languageEngine/python/processor/PythonProcessor.scala, src/main/scala/ai/privado/languageEngine/python/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/languageEngine/python/tagger/source/IdentifierTagger.scala
**Second Level derivation Implementation for Python**
- Tag identifier of all the typeDeclaration who have a PII as member
- Filter out **__iter__** and **__next__** calls from source tagging.
- Add isImport filter on astSiblings of Identifier to remove below **cookies** like identifiers
`from http import cookies`
=> Second Level derivation Implementation for Python

.github/workflows/comparison-results.yml
Passing `base` and `head` branch repo url info to comparison script.
=> Added input parameter to comparison script

src/main/scala/ai/privado/tagger/collection/WebFormsCollectionTagger.scala, src/test/scala/ai/privado/tagger/collection/WebFormsCollectionTaggerTest.scala
If the tag is split into multiple lines then the existing regex was failing to detect the element. Like the below code sample. Handled respective use case along with the addition of corresponding unit test
```
<ComplexInputField
name={FIELDS.SURNAME}
label={messages.surName.placeholder}
value={values?.surname}
error={errors.surname}
/>
```
=> Fix for failing use case

.github/workflows/code-quality.yml, .scalafmt.conf, build.sbt, src/main/scala/ai/privado/audit/AuditReportConstants.scala, src/main/scala/ai/privado/audit/DataElementDiscovery.scala, src/main/scala/ai/privado/dataflow/Dataflow.scala, src/main/scala/ai/privado/entrypoint/CommandParser.scala, src/main/scala/ai/privado/entrypoint/CommandProcessor.scala, src/main/scala/ai/privado/entrypoint/RuleValidator.scala, src/main/scala/ai/privado/entrypoint/ScanProcessor.scala, src/main/scala/ai/privado/entrypoint/UploadProcessor.scala, src/main/scala/ai/privado/exporter/ExporterUtility.scala, src/main/scala/ai/privado/exporter/SinkExporter.scala, src/main/scala/ai/privado/languageEngine/java/passes/read/DatabaseReadUtility.scala, src/main/scala/ai/privado/languageEngine/java/tagger/sink/FeignAPI.scala, src/main/scala/ai/privado/languageEngine/javascript/tagger/sink/JSAPITagger.scala, src/main/scala/ai/privado/languageEngine/python/semantic/PythonSemanticGenerator.scala, src/main/scala/ai/privado/passes/PropertyParserPass.scala, src/main/scala/ai/privado/passes/SQLParser.scala, src/main/scala/ai/privado/rulevalidator/YamlFileValidator.scala, src/main/scala/ai/privado/script/ExternalScalaScriptRunner.scala, src/main/scala/ai/privado/semantic/SemanticGenerator.scala, src/main/scala/ai/privado/tagger/utility/APITaggerUtility.scala, src/main/scala/ai/privado/utility/SQLParser.scala, src/main/scala/ai/privado/utility/Utilities.scala
* Scala 3 Upgrade Upgraded Joern and as minimal dependencies as possible to their compatible Scala 3 variant.
Note: [Mockito has no Scala 3 compatibility](https://index.scala-lang.org/mockito/mockito-scala) (yet) so we will have to disable it or find an alternative. The bad news is that this project has no clear path to [Scala 3](https://github.com/mockito/mockito-scala/issues/364#issuecomment-1192749274)
* Removing Mockito
* Updated Scala format to Scala 3
* Removed Scala 2.13 spec from code quality workflow
* Fixed Scala 3 compilation issues
* removed snakeyaml dependency
---------
=> Release 11 July 2023: Scala 3 Upgrade

src/main/scala/ai/privado/entrypoint/CommandParser.scala, src/main/scala/ai/privado/languageEngine/java/passes/read/DatabaseQueryReadPass.scala, src/main/scala/ai/privado/languageEngine/java/passes/read/DatabaseReadUtility.scala, src/main/scala/ai/privado/languageEngine/java/tagger/PrivadoTagger.scala, src/test/scala/ai/privado/languageEngine/java/passes/read/JavaSQLDatabaseReadTest.scala
There is a piece of code in `databaseReadPass` which runs Dataflow in runOnPart which is a resource-intensive task and becomes a bottleneck for repos like `openmrs-core` , I currently have added a flag  `disable-read-dataflow` and am able to get the repo scanned on the laptop using that flag. 
Default behaviour is to run the read dataflow, but for repos which need a higher configuration `disable-read-dataflow` can be used to skip the intensive task
The optimized version will be available in a follow-up PR
=> patch - remove the dataflow's reachableBy implementation from Read pass

build.sbt, src/main/scala/ai/privado/languageEngine/ruby/processor/RubyProcessor.scala, src/main/scala/ai/privado/languageEngine/ruby/tagger/sink/APITagger.scala, src/main/scala/ai/privado/languageEngine/ruby/tagger/source/IdentifierDerivedTagger.scala, src/main/scala/ai/privado/languageEngine/ruby/tagger/source/IdentifierTagger.scala, src/main/scala/ai/privado/model/Constants.scala
- Removed NaiveCalLinker for Ruby
- Upgraded to language engine version 2.0.78
- Increased Dataflow parameter expansion constant from 20 to 100- 
- Refactor in API Tagger of Ruby
=> Ruby API Flows (#716)

src/main/scala/ai/privado/exporter/JSONExporter.scala
The scala future used in the exporting step currently might leave some keys out of `privado.json` as it does not wait for the future to complete the `onComplete` step. This PR combines the adding to hashmap step and the processing steps into a single future, to make it atomic.
=> Fix: Parallel processing in JSON export.

src/main/scala/ai/privado/languageEngine/javascript/tagger/sink/JSAPITagger.scala, src/main/scala/ai/privado/model/Constants.scala, src/main/scala/ai/privado/passes/HTMLParserPass.scala, src/main/scala/ai/privado/utility/Utilities.scala, src/test/scala/ai/privado/passes/HTMLParserPassTest.scala
- Update HTMLParser to get HTML Elements excluding the script tag errors
- Update JSAPITagger to adopt HTMLElement in parsing
- Convert Inline script tag code into `content` attribute
=> Update the HTMLParser to adopt identifying script tags

build.sbt, src/main/scala/ai/privado/script/ExternalScalaScriptRunner.scala, src/test/scala/ai/privado/script/ExternalScalaScriptTest.scala
Using dotty `ScriptEngine` instead of scala reflection to run the external script. 
@khemrajrathore , please review.
=> Fix: External script processing to work with scala 3

src/main/scala/ai/privado/languageEngine/kotlin/processor/KotlinProcessor.scala
We are continuously observing the download dependency part for Kotlin fails leading to scan failure, also for getting types we have the TypeRecovery in place
=> Kotlin : Remove Download dependency

src/main/scala/ai/privado/languageEngine/java/passes/read/DatabaseReadUtility.scala, src/main/scala/ai/privado/languageEngine/java/tagger/Utility/SOAPTaggerUtility.scala, src/main/scala/ai/privado/languageEngine/java/tagger/sink/FeignAPI.scala, src/main/scala/ai/privado/languageEngine/java/tagger/source/IdentifierTagger.scala, src/main/scala/ai/privado/languageEngine/java/tagger/source/Utility.scala, src/main/scala/ai/privado/model/Constants.scala, src/main/scala/ai/privado/threatEngine/BackgroundScreenshot.scala
PR contains fix for performance issues faced in Kotlin Identifier tagger.
Reason was `callIn` returns duplicate nodes, so need to use `dedup` on top on `callIn` (The root cause can be incorrect AST structure for Kotlin frontend)
On top of it, have cached some queries in Identifier tagger, which helps in optimising the queries further
=> fix - performance issue due to callIn

src/main/scala/ai/privado/languageEngine/kotlin/tagger/collection/AndroidCollectionTagger.scala, src/main/scala/ai/privado/model/Constants.scala, src/test/scala/ai/privado/passes/AndroidXmlPassTest.scala
With this approach, we won't use source rules and directly use special collection rules for android forms. This improves tagging coverage since source rules were missing multiple androidXmlTagging node names which are usually very consistent (`emailEditText`, `email_edit_text` etc). This also allows us to add new rules fast and get them added as collections
This has a dependency on android collection rules PR: https://github.com/Privado-Inc/privado/pull/356
=> Use android collection rules for tagging

build.sbt, src/test/scala/ai/privado/script/ExternalScalaScriptTest.scala
To fix a test case `fork := true` was added in build.sbt, which is causing failure in aws codebuild
This PR reverts that
=> fix - aws codebuild timeout issue

src/main/scala/ai/privado/exporter/CollectionExporter.scala, src/main/scala/ai/privado/tagger/collection/AndroidCollectionTagger.scala
* sourceId is needed to be added as "tags" in android rules
* this is needed to link collections to sources
* also group and dedup collections
=> fix android collections source (#862)

.gitignore, log4j2.xml
**Context**:
Currently we are populating print statement and error log on console.
**Requirements**:
Logs getting printed on console should work as is and additional to that we need WARN logs from privado-core plus additional few libraries collected in a single file for debugging purpose.
**Changes**:
Console Logs: Addition to print statement we have added ERROR statement will be printed over console: https://github.com/Privado-Inc/privado-core/pull/884/files#diff-618cc4f8ed2a13c1d6cc9405f35994ddf20869ca42eec1438626d5ad9baf06d0R14
Logs collected in file: privado-core's DEBUG level and some other library's WARN level logs are collected: https://github.com/Privado-Inc/privado-core/pull/884/files#diff-618cc4f8ed2a13c1d6cc9405f35994ddf20869ca42eec1438626d5ad9baf06d0R20
=> Log4j: Changed console logs

src/main/resources/ai/privado/rulevalidator/schema/policies.json, src/main/resources/ai/privado/rulevalidator/schema/threats.json, src/main/scala/ai/privado/model/Config.scala, src/main/scala/ai/privado/model/Constants.scala, src/main/scala/ai/privado/policyEngine/PolicyExecutor.scala, src/test/scala/ai/privado/policyEngine/PolicyTests.scala, src/test/scala/ai/privado/threatEngine/GoThreatTests.scala
Trying to add below support 
```dataFlow:
sources:
- **          
sinks:
- **
sourceFilters:
allowedSourceFilters:
sources:
- "(?i)PhoneNumber"
sinkFilters:
allowedSinkFilters:
domains:
- "aws.amazon.com"```
=> Support allow filters in sources & sinks in Policies

build.sbt
use the updated version of goastgen to ignore the indirect dependencies
We made changes in `goastgen` utility to add metadata to go.mod.josn to filter out indirect dependencies. We updated the `goastgen` version inside main language engine build.sbt. However it wasn't updated inside `privado-core` hence it was downloading all the dependencies including the indirect one. With this change it will only download direct dependencies.
=> use updated version of goastgen to ignore the indirect dependencies

build.sbt
Bumping up the patch version allows us to utilise a newer JDK version based on earlier discussions. `stage` and `tests` work fine and I haven't noticed any issues.
=> Bump up Scala version to `3.3.1`

src/main/scala/ai/privado/entrypoint/Main.scala, src/main/scala/ai/privado/entrypoint/ScanProcessor.scala, src/main/scala/ai/privado/rulevalidator/YamlFileValidator.scala
1. Made changes in few log statments to log the complete stack trace.
2. Made changes to convert debug to trace logs for rule valiation.
3. Added exit(1) in main error handling situation, to indicate outer process that the scan failed. Made respective change in matric collection method calls as `finally` block will not be invoked after `exit(1)` call.
=> changed log handling and exit handling

build.sbt
This PR includes,
1. Bump up LE version to `2.0.244`
2. Bump up cpg version to `1.6.1`
=> Language engine and `cpg` version upgrade.

src/main/scala/ai/privado/entrypoint/CommandParser.scala, src/main/scala/ai/privado/passes/PropertyParserPass.scala
- add new flag `asset-discovery`
- skip reading `.privado` folder when running Property Pass
=> add asset discovery flag

src/main/scala/ai/privado/languageEngine/javascript/tagger/sink/JSAPITagger.scala, src/main/scala/ai/privado/tagger/sink/APITagger.scala
Changed JS API tagger to run the queries on `cpg.code` instead of methodFullName
=> Changed JS API tagger

src/main/scala/ai/privado/languageEngine/javascript/tagger/sink/JSAPITagger.scala, src/main/scala/ai/privado/tagger/sink/APITagger.scala
* Changed JS API tagger
Changed JS API tagger to run the queries on `cpg.code` instead of methodFullName
* including both method full name and code
* optimised the OR query
=> Changed JS API tagger (#956)

src/main/scala/ai/privado/audit/AuditReportConstants.scala, src/main/scala/ai/privado/audit/AuditReportEntryPoint.scala, src/main/scala/ai/privado/audit/LiteralReport.scala, src/test/scala/ai/privado/languageEngine/java/audit/LiteralReportTest.scala, src/test/scala/ai/privado/languageEngine/java/audit/LiteralReportTestBase.scala, src/test/scala/ai/privado/languageEngine/javascript/audit/HTTPReportTest.scala, src/test/scala/ai/privado/languageEngine/javascript/audit/HTTPReportTestBase.scala
- Added new sheet for `http` matched literal in audit report. 
- Done some refactoring, as some of the logic is common in the `URL` (having `\` matched literal ) and `HTTP` audit reports.
=> HTTP Audit Report

README.md, src/main/scala/ai/privado/languageEngine/java/tagger/collection/CollectionUtility.scala, src/test/scala/ai/privado/languageEngine/java/tagger/collection/CollectionUtilityTest.scala
**Description:**
This pull request addresses a critical issue where the actual URL of a collection is not correctly extracted under specific conditions. The bug manifests when the first parameter of annotations such as  @RequestMapping ,  @GetMapping ,  @PostMapping , etc., is something other than the intended URL. Previously, our logic incorrectly assumed that the first parameter always represented the URL. 
**Key Changes:** 
1. **Issue Identification:** Identified a breaking case where the extraction logic fails if the first parameter of the mapping annotation does not directly represent the URL. 
2. **Existing Logic Revision:** The existing extraction logic was limited to evaluating only the first parameter of the annotation, which led to inaccuracies in URL retrieval. 
3. **Focused …
=> Fix Extraction of URL from Request Mapping Annotations

src/main/scala/ai/privado/languageEngine/java/tagger/collection/CollectionUtility.scala, src/test/scala/ai/privado/languageEngine/java/tagger/collection/CollectionUtilityTest.scala
```
package com.example.demo;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
@RestController
@RequestMapping("/api") // Base URL for all methods in this controller
public class DemoController {
// This method inherits the URL from the class annotation
@GetMapping
public String getBase() {
return "This is the base API endpoint.";
}
// This method specifies its own URL
@GetMapping("/hello")
public String getHello() {
return "Hello from /api/hello!";
}
}
```
- **Class-Level  @RequestMapping**: The  @RequestMapping("/api")  annotation at the class level specifies that every method in this controller will be accessible under the  /api  base path unless the …
=> Default collection url: when url is not defined on immediate annotation

src/main/scala/ai/privado/exporter/HttpConnectionMetadataExporter.scala, src/test/scala/ai/privado/exporter/JavaLanguageEgressTest.scala, src/test/scala/ai/privado/exporter/JavaScriptLanguageEgressTest.scala, src/test/scala/ai/privado/exporter/PythonLanguageEgressTest.scala
- Cases Handled
-  String concatenation using addition operator 
-  String formatter operator
- Literal without any operation and getting assigned to a variable. 
- Implementation Details
- Collecting all literals that has slash in it and allowing some specific character to also support string formatter
- Filtering if only non alphanumeric symbols present
- remove \\" from all the strings
- go to call node(_we are not handling nested level concatination/formatting for now_) and collect strings based on the call node and their arguments
- The current logic is designed for Java, Python, and JavaScript, as I have tested it for these languages. I have not extended it to other languages yet, as literals can also appear in imports. In such cases, I will need to write additional logic to handle …
=> Add support to collect egress from code for js, python and java

src/main/scala/ai/privado/exporter/HttpConnectionMetadataExporter.scala, src/main/scala/ai/privado/languageEngine/java/tagger/collection/CollectionUtility.scala, src/test/scala/ai/privado/exporter/FeignEgressExportTest.scala
```
@FeignClient(name = "address-service", url = "http://localhost:8081", path = "/address-service")
public interface AddressClient {
@GetMapping(value = "/address/{id}")
public ResponseEntity<AddressResponse> getAddressByEmployeeId(@PathVariable("id") int id);
}
```
Requirement:
* Add base path as part of url.
- url generating before: **/address/{id}**
- url generating after change: **address-service/address/{id}**
Updated and verified existing test cases.
=> added base path for feign client

src/main/scala/ai/privado/exporter/ExporterUtility.scala, src/main/scala/ai/privado/exporter/HttpConnectionMetadataExporter.scala, src/main/scala/ai/privado/model/Constants.scala, src/test/scala/ai/privado/exporter/JavaLanguageEgressTest.scala, src/test/scala/ai/privado/exporter/JavaScriptLanguageEgressTest.scala, src/test/scala/ai/privado/exporter/PythonLanguageEgressTest.scala, src/test/scala/ai/privado/languageEngine/javascript/JavascriptTaggingTestBase.scala
- We need to analysis Egress From Code so moving them in a separate key 
- `<operator>.formatString` itself has some call nodes in case of python so instead of doing for language specific, replacing `{}` with empty string 
- Test cases were failing because of known language so explicitly set `AppCache.repoLanguage` in test cases
=> Store Egress from Code in a different key and remove parentheses from variable string

src/main/scala/ai/privado/languageEngine/go/passes/config/GoYamlLinkerPass.scala, src/main/scala/ai/privado/languageEngine/go/processor/GoProcessor.scala, src/main/scala/ai/privado/languageEngine/java/passes/config/JavaYamlLinkerPass.scala, src/main/scala/ai/privado/languageEngine/java/processor/JavaProcessor.scala, src/main/scala/ai/privado/languageEngine/java/tagger/sink/JavaAPITagger.scala, src/main/scala/ai/privado/passes/PropertyParserPass.scala, src/main/scala/ai/privado/passes/YamlLinkerPass.scala, src/main/scala/ai/privado/tagger/sink/APITagger.scala, src/main/scala/ai/privado/tagger/utility/APITaggerUtility.scala, src/test/scala/ai/privado/languageEngine/go/passes/config/GoYamlLinkerPassTest.scala, src/test/scala/ai/privado/languageEngine/java/passes/config/JavaYamlLinkerPassTest.scala, src/test/scala/ai/privado/languageEngine/java/passes/config/PropertiesFilePassTest.scala
- Added support to detect the internal flow having domain (i.e. `http://exampleService`) present inside the yaml file. 
- Made the implementation generic and can be used in anyLanguage, we only need to define the mapping rule between code and key.
=> API YamlLinkerPass support

src/main/scala/ai/privado/passes/SQLParser.scala, src/main/scala/ai/privado/utility/SQLParser.scala, src/test/scala/ai/privado/passes/SQLParserTest.scala
This PR includes a fix to display correct `lineNumber` of columns in a SQL query. This only includes queries from `.sql` files, as those queries are parsed individually.
=> [SQLParser] Fix SQL lineNumber when query is found in .sql file

src/main/scala/ai/privado/entrypoint/CommandParser.scala, src/main/scala/ai/privado/languageEngine/java/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/languageEngine/java/tagger/sink/JavaAPITagger.scala, src/main/scala/ai/privado/languageEngine/java/tagger/sink/api/JavaAPISinkByMethodFullNameTagger.scala, src/main/scala/ai/privado/languageEngine/java/tagger/sink/api/JavaAPISinkByParameterTagger.scala, src/main/scala/ai/privado/languageEngine/java/tagger/sink/api/JavaAPISinkTagger.scala, src/main/scala/ai/privado/model/Constants.scala, src/main/scala/ai/privado/model/PrivadoTag.scala, src/main/scala/ai/privado/tagger/sink/api/APISinkTagger.scala, src/test/scala/ai/privado/RuleInfoTestData.scala, src/test/scala/ai/privado/languageEngine/java/JavaTestBase.scala, src/test/scala/ai/privado/languageEngine/java/tagger/sink/api/JavaAPISinkByMethodFullNameTaggerTest.scala, src/test/scala/ai/privado/languageEngine/java/tagger/sink/api/JavaAPISinkByParameterTaggerTest.scala, src/test/scala/ai/privado/model/SourceCodeModel.scala
This PR contains
- Support for tagging API by methodFullName by specifying the regex in `privado->config->systemConfig->file.yaml` under the key `apiMethodFullNames`
- Support for tagging API by deriving API client by looking at the parameter names, this has been kept under the flag `enable-api-by-parameter` for now
This PR also proposes to refactor the current API tagger implementation such as tagging API sinks as `API_SINK_MARKED`, based on respective detection logic.
All these tagged API's can be collected in the APITagger and dataflow from literal to them can be computed and tagged appropriately
=> add support to tag api by matching url like parameter

src/main/scala/ai/privado/exporter/HttpConnectionMetadataExporter.scala, src/test/scala/ai/privado/languageEngine/java/passes/config/PropertiesFilePassTest.scala
Changes: Eliminating egress urls such as filename, aws urls or html template which is matching existing pattern(string having slash)
After adding this elimination pattern around 90% entries are reduced.
Also enabled one of test case which is marked ignored last time.
=> product level datamap: exclude false positive entries from egress

src/main/scala/ai/privado/languageEngine/php/processor/PhpProcessor.scala
Vendored utilities are copied to a different path as part of Docker's build steps (ref. to the last couple of `COPY` commands in `Dockerfile`). Because this was not accounted for in the previous integration PR, there was an issue running a scan on PHP repositories. This PR fixes it.
=> fix: incorrect PHP parser vendoring

src/test/scala/ai/privado/languageEngine/csharp/CSharpTestCpgBase.scala, src/test/scala/ai/privado/languageEngine/kotlin/KotlinTestCpgBase.scala, src/test/scala/ai/privado/languageEngine/php/PhpTestCpgBase.scala
Created abstract Language specific TestBaseCpg for Php, CSharp, Kotlin.
Ruby, Python, Javascript, GoLang are currently out of scope as they don't extend the BaseProcessor, there are tech debts for now, which needs to be picked in future PR's
=> add - test cpg base for languages

build.sbt, src/main/scala/ai/privado/passes/HTMLParserPass.scala
Resolved very critical vulnerability in net.sourceforge.htmlunit by replacing it with org.htmlunit
=> updated htmlunit version (#1057)

src/main/scala/ai/privado/languageEngine/csharp/processor/CSharpProcessor.scala, src/main/scala/ai/privado/languageEngine/csharp/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/languageEngine/csharp/tagger/sink/CSharpAPISinkTagger.scala, src/main/scala/ai/privado/languageEngine/csharp/tagger/sink/CSharpAPITagger.scala, src/test/scala/ai/privado/languageEngine/csharp/CSharpTestBase.scala, src/test/scala/ai/privado/languageEngine/csharp/tagger/sink/CSharpAPITaggerTest.scala
Adds basic API tagging with support for `System.Net.Http` based API calls
=> CSharp: Basic API tagger

src/main/scala/ai/privado/audit/DataElementDiscovery.scala, src/test/scala/ai/privado/languageEngine/java/audit/DataElementDiscoveryTest.scala
Filter out classes in the data element discovery of the audit report that have no member variables defined.
=> Member filter in data element discovery

src/main/scala/ai/privado/audit/AuditReportConstants.scala, src/main/scala/ai/privado/audit/AuditReportEntryPoint.scala, src/main/scala/ai/privado/audit/DataElementDiscovery.scala, src/test/scala/ai/privado/languageEngine/java/audit/DataElementDiscoveryTest.scala
This PR adds the functionality for recording line numbers when generating audit sources and modifies existing tests accordingly.
=> Add lineNumber, variableId & nodeType in audit sources report

src/main/scala/ai/privado/audit/AuditReportEntryPoint.scala, src/main/scala/ai/privado/languageEngine/go/processor/GoProcessor.scala, src/main/scala/ai/privado/languageEngine/python/processor/PythonProcessor.scala, src/test/scala/ai/privado/languageEngine/go/audit/DataElementDiscoveryTest.scala, src/test/scala/ai/privado/languageEngine/go/audit/DataElementDiscoveryTestBase.scala, src/test/scala/ai/privado/languageEngine/go/audit/TestData/AuditTestClassData.scala, src/test/scala/ai/privado/languageEngine/python/audit/DataElementDiscoveryTest.scala, src/test/scala/ai/privado/languageEngine/python/audit/DataElementDiscoveryTestBase.scala, src/test/scala/ai/privado/languageEngine/python/audit/TestData/AuditTestClassData.scala
Adds audit sources support for Go and Python. Opened a new PR over #1125 as it was outdated and had too many conflicts.
=> Add audit sources support for Go and Python

updateDependencies.sh
Changes: 
1. Use `jq` instead of `xmllint` to parse response. ( GH Packages works with json )
PS: Would require a GH token in the environment to run this because the package registry is private to an organization.
=> Change `updateDependencies.sh` to resolve versions from GH packages

src/main/scala/ai/privado/audit/AuditReportConstants.scala, src/main/scala/ai/privado/audit/AuditReportEntryPoint.scala, src/main/scala/ai/privado/audit/DataElementDiscovery.scala, src/main/scala/ai/privado/languageEngine/go/processor/GoProcessor.scala, src/main/scala/ai/privado/languageEngine/python/processor/PythonProcessor.scala, src/main/scala/ai/privado/languageEngine/ruby/processor/RubyProcessor.scala, src/test/scala/ai/privado/languageEngine/go/audit/DataElementDiscoveryTest.scala, src/test/scala/ai/privado/languageEngine/java/audit/DataElementDiscoveryTest.scala, src/test/scala/ai/privado/languageEngine/python/audit/DataElementDiscoveryTest.scala
- For each language what support tobe  added mentioned in doc: https://privado-ai.atlassian.net/wiki/spaces/arc/pages/979009551/DED+Audit+Report+Data
- Add support for the Csharp, PHP, Ruby, Golang & Python
- Moved the common utilities in DataElementDiscoveryUtils
- Created single functions getIdentifiers, getFieldAccessIdentifier, getMemberUsingClassName to add support for those inline
- Added some common filters & language specific filters to remove noise from audit sources.
- Also, handled possibel error comes due to invalid regex pattern in **XX.typeFullName**
=> Update the audit sources support for JS, Python, PHP, Go & CSharp

src/main/scala/ai/privado/entrypoint/CommandParser.scala, src/main/scala/ai/privado/entrypoint/MetadataProcessor.scala, src/main/scala/ai/privado/entrypoint/ScanProcessor.scala, src/main/scala/ai/privado/metadata/SystemInfo.scala, src/main/scala/ai/privado/model/Constants.scala
The PR introduces a new command `metadata`, which captures system level information and dumps the info in `.privado/systemInfo.json`
```
{
"operatingSystemInfo" : {
"name" : "Mac OS X",
"version" : "14.3",
"architecture" : "aarch64",
"processorCount" : 11
},
"systemMemoryInfo" : {
"memorySizeInGB" : 18,
"swapSizeInGB" : 2
},
"systemDiskInfo" : {
"fileStoreName" : "/dev/disk3s5",
"totalSpaceInGB" : 460,
"freeSpaceInGB" : 253
}
}
```
=> add support for metadata command

src/test/scala/ai/privado/languageEngine/php/tagger/source/FieldIdentifierTaggingTests.scala, src/test/scala/ai/privado/languageEngine/php/tagger/source/IdentifierTaggingTest.scala, src/test/scala/ai/privado/languageEngine/php/tagger/source/LiteralTaggingTests.scala
PR refactors tests to use `*FrontendTestSuite`.
=> PHP: Migrate older test suites to newer ones

src/main/scala/ai/privado/languageEngine/csharp/tagger/sink/CSharpAPISinkTagger.scala, src/main/scala/ai/privado/languageEngine/go/tagger/sink/GoAPISinkTagger.scala, src/main/scala/ai/privado/languageEngine/javascript/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/languageEngine/javascript/tagger/sink/JSAPISinkTagger.scala, src/main/scala/ai/privado/languageEngine/php/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/languageEngine/php/tagger/sink/PhpAPISinkTagger.scala, src/main/scala/ai/privado/languageEngine/python/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/languageEngine/python/tagger/sink/PythonAPISinkTagger.scala, src/main/scala/ai/privado/languageEngine/ruby/tagger/PrivadoTagger.scala, src/main/scala/ai/privado/languageEngine/ruby/tagger/sink/RubyAPISinkTagger.scala, src/main/scala/ai/privado/tagger/sink/api/APISinkByMethodFullNameTagger.scala
The PR adds
- support of adding inference API rules across languages
- support for taking API sink via methodFullName regex
- Refactor to make this available across
=> refactor and make sure to use the trait as base for all ApiSinkTagger

build.sbt
Upgraded to fix vulnerabilities introduced by go version 1.18. 
Refer commit on goastgen:  https://github.com/Privado-Inc/goastgen/commit/458e417717a9a09eb65c3695e02e6450c8f1405f
=> Upgrade `goastgen`

src/main/scala/ai/privado/languageEngine/java/tagger/sink/api/JavaAPITagger.scala, src/main/scala/ai/privado/languageEngine/javascript/tagger/sink/JSAPITagger.scala, src/main/scala/ai/privado/languageEngine/php/tagger/sink/APITagger.scala, src/main/scala/ai/privado/languageEngine/python/tagger/sink/PythonAPITagger.scala, src/main/scala/ai/privado/languageEngine/ruby/tagger/sink/APITagger.scala, src/main/scala/ai/privado/tagger/sink/APITagger.scala, src/main/scala/ai/privado/tagger/utility/APITaggerUtility.scala, src/test/scala/ai/privado/tagger/TaggerValidator.scala, src/test/scala/ai/privado/tagger/sink/LeakageValidator.scala, src/test/scala/ai/privado/tagger/sink/api/APIValidator.scala, src/test/scala/ai/privado/tagger/sink/api/InferenceAPIEndpointTaggerTest.scala
Context - We run inference tagger to tag API, and after than we run a API Tagger.
API's already tagged by inference, shouldn't process with API Tagger, so we have added a filtering in `sinkTagger` utility which was currently only applied for Java. But as we have opened up the inference tagger for other language as well, having it at a common place is ideal.
=> filter out already tagged api sinks

src/main/resources/ai/privado/rulevalidator/schema/inferences.json, src/main/scala/ai/privado/entrypoint/DynamicRuleMerger.scala, src/main/scala/ai/privado/model/PrivadoTag.scala
The PR adds patch for
- Rule validation on inferences to support passing rules for endpoint_domain_with_literal and endpoint_domain_with_property_name
- domain.headOption.get can result into error for rules having empty domains and needs to be handled- Reverting this change as it is causing issue in comparison report, @ankit-privado Needs to look into why this is happening - ThirdParties.SDK.Google.Firebase in Java comparison report
=> update validation for inference rule

src/main/scala/ai/privado/entrypoint/CommandParser.scala, src/main/scala/ai/privado/languageEngine/base/processor/BaseProcessor.scala, src/main/scala/ai/privado/languageEngine/javascript/processor/JavascriptBaseCPGProcessor.scala
For metadata scan we just need the Base CPG, so no need to run Dataflow passes
=> skip running dataflow passes in metadata scan

src/main/scala/ai/privado/entrypoint/DynamicRuleMerger.scala
Earlier, it was throwing an error because the domain was empty for some of the sink rules like `Logs`, `Internal APIs`, `Cookie`. So, I added a filter to those rules where the domain or name is empty, because our merging logic relies on these two parameters, and they need to be present.
=> Dynamic rule fix

src/main/scala/ai/privado/cache/RuleCache.scala, src/main/scala/ai/privado/inputprocessor/DynamicRuleMerger.scala, src/main/scala/ai/privado/inputprocessor/RuleProcessor.scala, src/main/scala/ai/privado/tagger/sink/DependencyNodeTagger.scala, src/test/scala/ai/privado/inputprocessor/DynamicRuleMergerTest.scala, src/test/scala/ai/privado/languageEngine/java/tagger/sink/DependencyTaggerTest.scala
When we merge an external rule with an internal one, it's possible that both merging rules don't have the same ID. In cases where the domain or name matches, we merge the external rule with the internal one, but when tagging the dependency node, we only have the external rule ID. So, it's important to map which external rule was merged with which internal rule.
We have created the `DynamicMergerRuleMap` to store the merging information.
=> Dynamic Rule Merger Fix
